def on_on_created(sprite):
    global mySprite2
    mySprite2 = sprites.create(img("""
            . . . . . . c c c . . . . . . .
            . . . . . . c 5 b c . . . . . .
            . . . . c c c 5 5 c c c . . . .
            . . c c c c 5 5 5 5 c b c c . .
            . c b b 5 b 5 5 5 5 b 5 b b c .
            . c b 5 5 b b 5 5 b b 5 5 b c .
            . . c 5 5 5 b b b b 5 5 5 f . .
            . . f f 5 5 5 5 5 5 5 5 f f . .
            . . f f f b f e e f b f f f . .
            . . f f f 1 f b b f 1 f f f . .
            . . . f f b b b b b b f f . . .
            . . . e e f e e e e f e e . . .
            . . e b f b 5 b b 5 b c b e . .
            . . e e f 5 5 5 5 5 5 f e e . .
            . . . . c b 5 5 5 5 b c . . . .
            . . . . . f f f f f f . . . . .
            """),
        SpriteKind.enemy)
sprites.on_created(SpriteKind.enemy, on_on_created)

def on_up_released():
    controller.move_sprite(mySprite)
controller.up.on_event(ControllerButtonEvent.RELEASED, on_up_released)

def on_on_created2(sprite2):
    pass
sprites.on_created(SpriteKind.player, on_on_created2)

mySprite2: Sprite = None
mySprite: Sprite = None
tiles.set_current_tilemap(tilemap("""
    level0
    """))
mySprite = sprites.create(img("""
        ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf2222f4e...........
        fbbbbf2222fd4...........
        .fccf45544f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        """),
    SpriteKind.player)

def on_forever():
    scene.camera_follow_sprite(mySprite)
forever(on_forever)
